variables:
  openzwave: '1.6.943'

jobs:
  - template: docker-build.yml
    parameters:
      build_arch: amd64
      qemu_arch: x86_64
      openzwave: $(openzwave)
  - template: docker-build.yml
    parameters:
      build_arch: arm32v6
      qemu_arch: arm
      openzwave: $(openzwave)
  - template: docker-build.yml
    parameters:
      build_arch: arm64v8
      qemu_arch: aarch64
      openzwave: $(openzwave)
