jobs:
- job: ${{ parameters.build_arch }}
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    BUILD_ARCH: ${{ parameters.build_arch }}
    QEMU_ARCH: ${{ parameters.qemu_arch }}
    OPENZWAVE_VERSION: ${{ parameters.openzwave }}
  steps:
    - task: Docker@0
      displayName: 'Enable qemu'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryConnection: 'mlankamp-docker'
        action: 'Run a Docker command'
        customCommand: 'run --rm --privileged multiarch/qemu-user-static:register --reset'

    - task: Docker@2
      displayName: 'Build image'
      inputs:
        containerRegistry: 'mlankamp-docker'
        repository: 'mlankamp/node-openzwave'
        command: build
        arguments: '--build-arg BUILD_ARCH=$(BUILD_ARCH) --build-arg QEMU_ARCH=$(QEMU_ARCH) --build-arg OPENZWAVE_VERSION=$(OPENZWAVE_VERSION) --add-host old.openzwave.com:184.106.179.216'
        tags: |
          $(BUILD_ARCH)-$(OPENZWAVE_VERSION)
          $(BUILD_ARCH)-latest
        addPipelineData: false

    - task: Docker@2
      displayName: 'Push image'
      inputs:
        containerRegistry: 'mlankamp-docker'
        repository: 'mlankamp/node-openzwave'
        command: push
        tags: |
          $(BUILD_ARCH)-$(OPENZWAVE_VERSION)
          $(BUILD_ARCH)-latest
        addPipelineData: false
